[package]
name = "essaymind"
version = "0.1.0"
edition = "2021"
publish=false

[lib]
name = "essaymind"
crate-type = ["cdylib"]
path = "rust/src/lib.rs"

[dependencies]
pyo3 = { version = "0.18.0", features = ["extension-module"] }
core_lib = { path = "rust/core_lib"}

[workspace]
members = [
    "rust/core_lib",
]

[package.metadata.maturin]
name="essaymind._essaymind"
