[package]
name = "essaymind"
version = "0.1.9"
edition = "2021"
publish=false

[lib]
name = "essaymind"
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
env_logger = { version = "0.10.0" }
log = { version = "0.4.17" }

[workspace]
members = [
    "crates/*",
]

[workspace.dependencies]
ticker = { path = "./crates/ticker", version = "0.0.0" }
