[package]
name = "essaymind"
version = "0.1.0"
edition = "2021"
publish=false

[lib]
name = "essaymind"
crate-type = ["cdylib"]
path = "crates/src/lib.rs"

[dependencies]
env_logger = { version = "0.10.0" }
log = { version = "0.4.17" }
ticker = { path = "crates/ticker"}

[workspace]
members = [
    "crates/ticker",
]

[package.metadata.maturin]
name="essaymind._essaymind"
