[package]
name = "essay-ecs-app"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { version = "0.4.17" }
env_logger = { version = "0.10.0" }
essay-ecs-core = { path = "../essay-ecs-core" }
essay-ecs-app-macros = { path = "macros" }

[lib]
doctest = false
