[package]
name = "sound"
version = "0.0.0"
edition = "2021"

[dependencies]
log = { version = "0.4.17" }
env_logger = { version = "0.10.0" }
# kira = { version="0.7" }
symphonia = { version="0.5" }

[lib]
doctest = false

