[package]
name = "essay-ecs-core"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { version = "0.4.17" }
fixedbitset = "0.4"
concurrent-queue = "2.2"
essay-ecs-core-macros = { path = "macros", version = "0.1.0" }

[lib]
doctest = false
